version: '1.0'

services:
  backend:
    build:
      context: .
    container_name: kronos_backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG:True
      - DJANGO_ALLOWED_HOSTS=*
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: b13rt-Osmani
      POSTGRES_DB: kronos