# Generated by Django 5.1.4 on 2024-12-23 08:37

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_assignee_remove_task_reporter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', datetime.datetime(2024, 12, 23, 8, 37, 23, 771043, tzinfo=datetime.timezone.utc))), name='due_date_not_in_past'),
        ),
    ]
