# Generated by Django 5.1.4 on 2024-12-23 08:42

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_due_date_not_in_past'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='due_date_not_in_past',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', datetime.datetime(2024, 12, 23, 8, 42, 5, 359957, tzinfo=datetime.timezone.utc))), name='due_date_not_in_past'),
        ),
    ]
